### ISSUE TITLE
What about mapped virtual keys?

### ISSUE THREAD

**Issue by dtapuska** [garykac/system-keyboard-lock#14]
Will anyone want actually mapped keys? Not specifically games or chromoting (where the keyboard layout is irrevlant to the webpage). But say someone wants to provide their own Ctrl-P (printing functionality). How do they know that on dvorak keyboard they need to actually register the 'R' in this API to get that functionality? But on a qwerty keyboard they use 'P'. 

The fact that the page doesn't know the current keyboard layout and when the keyboard layout changes can be difficult to implement that functionality on top of this API. Perhaps these aren't cases we need to solve.

@smaug----  Probably someone from Gecko might have some feedback on this proposal.

**Comment by smaug----** [comment]
I think I'm missing what the actual question here is.

@masayuki-nakano might have some feedback here too.

**Comment by garykac** [comment]
The spec uses |code| (and not |key|) to specify keys because we could not think of any cases that required |key|. We're not against adding support if needed, but:
* it complicates the API and make it more confusing for developers (should I specify |key| or |code|?), so we don't want to do it unless it is necessary
* we can add support for |key| later if needed

Note that Mac OS provides Dvorak and Dvorak-QWERTY layouts to partially address the Dvorak issue you raise. For the Dvorak-QWERTY layout the Cmd/Ctrl keys use Qwerty instead of Dvorak.

**Comment by masayuki-nakano** [comment]
Similarly, if you create Dvorak keyboard layout with MSKLC, virtual keycode is generated with QWERTY keyboard layout but WM_CHAR is generated with Dvorak keyboard layout. Although, Firefox doesn't support this case with key value and supporting it might break current key value spec's explanation.

https://bugzilla.mozilla.org/show_bug.cgi?id=434737

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#14
