### ISSUE TITLE
Links to http://www.w3.org/TR/systemkeylock/ and https://github.com/w3c/systemkeylock/ are 404

### ISSUE THREAD

**Issue by foolip** [garykac/system-keyboard-lock#17]
They're linked from the top of https://garykac.github.io/system-keyboard-lock/

Relatedly, please pick a single "shortname" and use it everywhere. In https://codereview.chromium.org/2805763004 tests are being added under keyboard-lock/ in web-platform-tests. Bikeshed: I prefer that to the longer system-keyboard-lock.

**Comment by garykac** [comment]
We were originally using "system keyboard lock" when we were considering a
separate spec for "browser key lock" to avoid confusion.

Because we're no long considering a separate spec, we're changing the name
to simply keyboard-lock, but we didn't want to break any existing links to
the temp spec.

The intent is to rename fully when we migrate to W3C.

Thanks for the comment, I appreciate your attention to details like this.

**Comment by foolip** [comment]
Great, keyboard-lock everywhere eventually then :)

**Comment by garykac** [comment]
This issue was moved to w3c/keyboard-lock#17
